version: '3.8'

services:
  DoD:
    build: .
    image: it-crm-flask:v0.1
    container_name: DoD
    ports:
      - "5000:5000"
    networks:
      - DoD-CRM-NETWORK
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: DoD_CRM_DATABASE_25
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - DoD-CRM-NETWORK

networks:
  DoD-CRM-NETWORK:
    driver: bridge

volumes:
  postgres_data:
